spring:
  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/taskmanager
          jwk-set-uri: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

server:
    port: 8081